name: Run RakutenPay2MoneyForwardME

on:
  schedule:
    # 毎日午前6時 JST（=21:00 UTC）
    - cron: "0 21 * * *"
  workflow_dispatch: # 手動実行も可能

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          TESTMAIL_API_KEY: ${{ secrets.TESTMAIL_API_KEY }}
          TESTMAIL_NAMESPACE: ${{ secrets.TESTMAIL_NAMESPACE }}
          TESTMAIL_TAG: ${{ secrets.TESTMAIL_TAG }}
          MONEY_FORWARD_EMAIL: ${{ secrets.MONEY_FORWARD_EMAIL }}
          MONEY_FORWARD_PW: ${{ secrets.MONEY_FORWARD_PW }}
        run: npm start

